
# KNN Classification Tutorial with Python

## Step 1: Setup

Ensure you have the necessary Python libraries. We'll use `scikit-learn` for KNN and `numpy` for data handling. Install them using pip if you don't have them:

```python
!pip install scikit-learn numpy
```

## Step 2: Import Libraries

In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

## Step 3: Load the Dataset

We will use the Iris dataset, a classic in machine learning. It contains measurements of iris flowers and their species.

In [2]:
iris = load_iris()
X, y = iris.data, iris.target
X.shape

(150, 4)

In [3]:
print(X[0:5,:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


## Step 4: Split the Data

Split our data into a training set and a test set.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


## Step 5: Create and Train the KNN Model

Create our KNN model. Let's start with `k=3`.

In [5]:
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

## Step 6: Make Predictions

Use our trained model to make predictions on our test set.

In [6]:
predictions = knn.predict(X_test)
predictions

c:\Users\ebrahim.alwajih\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

## Step 7: Evaluate the Model

Use accuracy as our evaluation metric — the fraction of correctly classified instances.

In [7]:
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


## Conclusion

You've built and evaluated your first KNN classification model! Experiment with different values of `k` and see how it affects the model's performance.
